# Lo que usa el observatorio de h3 (https://github.com/uber/h3-py, Apache 2.0).

__version__: str

def latlng_to_cell(lat: float, lng: float, res: int) -> str: ...
def cell_to_latlng(h: str) -> tuple[float, float]: ...
def grid_disk(h: str, k: int = 1) -> list[str]: ...
def average_hexagon_area(res: int, unit: str = "km^2") -> float: ...
def cell_to_boundary(h: str) -> tuple[tuple[float, float], ...]: ...
