# Tipos mínimos de pyrage: la biblioteca no publica anotaciones.
from collections.abc import Sequence

from . import x25519 as x25519

class EncryptError(Exception): ...
class DecryptError(Exception): ...
class IdentityError(Exception): ...
class RecipientError(Exception): ...

def encrypt(plaintext: bytes, recipients: Sequence[x25519.Recipient]) -> bytes: ...
def decrypt(ciphertext: bytes, identities: Sequence[x25519.Identity]) -> bytes: ...
